### PR TITLE
Adaridge Columns all added

### PR DESCRIPTION
**Pull request by NathanSalapat**
Adaridge as a block type is hereby finished.

### CODE REVIEW

**Comment by DonBatman** [comment]
I was wondering if you wanted to add the blocks from myholeinthewall mod.
https://github.com/DonBatman/myholeinthewall

**Comment by NathanSalapat** [comment]
I don't know if those would really fit with the theme of the mod, as this is mostly exterior hardscape type stuff, the myholeinthewall nodes seem to be more for in walls in grand buildings, though I suppose they could be used for a wall too, though we'd have to decided if they were going to be as thick as a full node, or not, and if not where they would be located in the node space. I personally think that having them a full node thick would be too thick, but then if you wanted to use them as a retaining wall of sorts there would be an empty space between them and the dirt material behind them. Of course they could be set so they would line up with the node behind them, but then if you wanted to use them in a building, there would be these goofy indents in the walls in every place where one of those were used.

**Comment by DonBatman** [comment]
I do not like the full blocks. 
These blocks are used for gardens to make walls and fences.
http://www.kelleyconcrete.com/wp-content/uploads/concrete%20block%20fence.jpg

**Comment by NathanSalapat** [comment]
Ah, I could probably work that in on the Deco page.

**Comment by DonBatman** [comment]
It was just a thought. If you do not want it in your mod then I am ok with that. 
I just thought that it is a concrete product so it might fit in. If you do include it then you might want to exclude the full block and add a 1/4 block. 
Great job on the new wall style. It looks awesome. Your dragon is even better. You are amazing with blender.

**Comment by NathanSalapat** [comment]
I think I'll add them in, they could go well between columns, Depending on
the style of the block I may just do them as half blocks and make it so
when you place two half blocks on top of each other you get a full block,
this would make them a little more versatile for a wider range of uses.

**Pull request merged**
