### PR TITLE
updated formspec for mixer, some new walls.

### PR DESCRIPTION
**Pull request by NathanSalapat**
As I mentioned in the email I pulled the formspec out of the mixer.lua and created a new file for that, I think it keeps things a little neater, and help keep the size of the mixer.lua a bit shorter.
I added in buttons for the decorative walls, we can finally make those without cheating to get them. LOL
There are more block walls I want to create as can be seen from the retaining wall formspec tab.
I would have created some more patio pavers, but I see you did those all as nodeboxes, which I don't know how to work with, I tried getting the NBE once, but couldn't get it to work on Linux very well.

### CODE REVIEW

**Comment by DonBatman** [comment]
I use NBE on linux and have no issue with it. I just unzipped it and went into the bin folder and run it from there. I can make some if you need me to or you can change out the ones I made for mesh nodes. You can do as you please with the mod. 
I am anxious to see the new walls. Will be great to have more building material.

**Comment by NathanSalapat** [comment]
Hmm, maybe it's been updated since I last used it. I'll give it a whirl, though I may just export your designs as mesh and then do everything as OBJs as I'm far more familiar with Blender.

**Comment by DonBatman** [comment]
Remember that you need 2  for each design. One is a full height block and the other is the think block. 
If you do them in blender you might get a better looking block. Let me know how it works out.

**Comment by NathanSalapat** [comment]
The designs with diagonals will look much better in Blender, than the NBE, and I know how to do textures in Blender far better than I ever figured out for NBE.

**Comment by DonBatman** [comment]
No doubt that mesh nodes look better if you know how. I do not know how to use Blender. I have not taken the time to learn yet. One of these days I will learn so I can change some of my mods over to mesh. The millwork mod would look so good as rounded mesh nodes.

**Pull request merged**
